<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsLambdaProject>true</IsLambdaProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
    <PackageReference Include="AWSSDK.SQS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Ingest.Storage\Ingest.Storage.csproj" />
  </ItemGroup>

</Project>
