<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsLambdaProject>true</IsLambdaProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
    <PackageReference Include="AWSSDK.ApiGatewayManagementApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Notifier.Storage\Notifier.Storage.csproj" />
  </ItemGroup>

</Project>
